mod recursive_atr_test;
mod recursive_batch_validator_test;
mod recursive_cross_over_test;
mod recursive_cross_under_test;
mod recursive_ema_test;
mod recursive_lifo_test;
mod recursive_rma_test;
mod recursive_rsi_test;
mod recursive_sma_test;
